"""add membership and invite tables

Revision ID: e0620d084a97
Revises: 30b773ebb66d
Create Date: 2026-08-31 23:11:46.716215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0620d084a97'
down_revision: Union[str, Sequence[str], None] = '30b773ebb66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board_invites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_board_invites_board_id'), 'board_invites', ['board_id'], unique=False)
    op.create_table('board_members',
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['boards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('board_id', 'user_id')
    )
    op.create_index(op.f('ix_board_members_user_id'), 'board_members', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: every existing board's owner becomes an owner-member, so the
    # membership table is authoritative from the moment it exists.
    op.execute(
        """
        INSERT INTO board_members (board_id, user_id, role, created_at)
        SELECT id, owner_id, 'owner', created_at FROM boards
        ON CONFLICT DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_members_user_id'), table_name='board_members')
    op.drop_table('board_members')
    op.drop_index(op.f('ix_board_invites_board_id'), table_name='board_invites')
    op.drop_table('board_invites')
    # ### end Alembic commands ###
